<a href="https://colab.research.google.com/github/KatBCN/ML-PropertyAssessment/blob/main/ML_DataSplit_PropertyAssessment_Buffalo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Splitting into Train / Validation / Test

In this notebook, we will follow the code example show in Lab 4 in order to partition the data prior to developing our pre-process and training pipeline.

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

In [2]:
pd.set_option('display.max_columns', None)  #set display to show all columns

We import the data from our [GitHub repository](https://github.com/KatBCN/ML-PropertyAssessment).

In [3]:
data_link = "https://raw.githubusercontent.com/KatBCN/ML-PropertyAssessment/main/Data/2019-2020_Assessment_Roll.csv"
df = pd.read_csv(data_link)

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (23) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [4]:
# Show number of rows and columns in dataframe
df.shape

(93862, 51)

In [5]:
# Show column names
df.columns

Index(['SBL', 'Tax District', 'Print Key', 'Front', 'Depth', 'Property Class',
       'Property Class Description', 'Previous Property Class', 'Owner1',
       'Owner2', 'Previous Owner', 'Mail1', 'Mail2', 'Mail3', 'Mail4',
       'House Number', 'Street', 'Address', 'City', 'State', 'Zipcode',
       'Zipcode Extension', 'Deed Book', 'Deed Page', 'Deed Date', 'Roll',
       'Land Value', 'Total Value', 'Sale Price', 'Year Built',
       'First Story Area', 'Second Story Area', 'Total Living Area',
       'Overall Condition', 'Building Style', 'Heat Type', 'Basement Type',
       '# of Stories', '# of Fireplaces', '# of Beds', '# of Baths',
       '# of Kitchens', 'Council District', 'Police District', 'Census Tract',
       'Census Block Group', 'Census Block', 'Neighborhood', 'Latitude',
       'Longitude', 'Location'],
      dtype='object')

In [6]:
df.head()

,SBL,Tax District,Print Key,Front,Depth,Property Class,Property Class Description,Previous Property Class,Owner1,Owner2,Previous Owner,Mail1,Mail2,Mail3,Mail4,House Number,Street,Address,City,State,Zipcode,Zipcode Extension,Deed Book,Deed Page,Deed Date,Roll,Land Value,Total Value,Sale Price,Year Built,First Story Area,Second Story Area,Total Living Area,Overall Condition,Building Style,Heat Type,Basement Type,# of Stories,# of Fireplaces,# of Beds,# of Baths,# of Kitchens,Council District,Police District,Census Tract,Census Block Group,Census Block,Neighborhood,Latitude,Longitude,Location
0,1113100012001122A,147003.0,111.31-12-1.122/A,0.00,0.00,873,GAS MEAS STATION,873.0,NATIONAL FUEL GAS DIST,CORP,NaN,NaN,NaN,6363 MAIN ST,"WILLIAMSVILLE, NY",725.0,WASHINGTON,NaN,BUFFALO,NY,14203.0,NaN,NaN,NaN,09/09/9999,6,0,13006,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1011500001001111,147012.0,101.15-1-1.111,0.00,0.00,330,COMMERCIAL VACANT LAND,330.0,"AROUND THE CLOCK CAR WASH,INC.",NaN,NaN,NaN,NaN,6547 EMILY LN,"LOCKPORT, NY",119.0,WEX,NaN,BUFFALO,NY,14211.0,NaN,11144,9356.0,09/09/9999,1,2900,2900,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0785000008001000,147009.0,78.50-8-1,65.00,82.57,311,RESIDENTIAL VACANT LAND,NaN,THE MARRANO/MARC-EQUITY CORP.,NaN,NaN,NaN,NaN,2730 TRANSIT RD,"WEST SENECA, NY",142.0,RACHEL VINCENT,NaN,BUFFALO,NY,14216.0,NaN,11331,1637.0,09/09/9999,1,1700,1700,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1007300008009111,147003.0,100.73-8-9.111,50.00,200.00,311,RESIDENTIAL VACANT LAND,311.0,MARIAH LORETTA LLC,NaN,NaN,NaN,NaN,100 S WOODLAND RIDGE,"ELMA, NY",289.0,LOCUST,NaN,BUFFALO,NY,14204.0,NaN,11309,505.0,09/09/9999,1,3800,3800,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1321500002004000,147013.0,132.15-2-4,521.34,1184.60,340,INDUSTRIAL VACANT LAND,340.0,BUFFALO URBAN DEVELOPMENT CORP,NaN,NaN,NaN,NaN,275 OAK ST,"BUFFALO, NY",126.0,LABORERS WAY,NaN,BUFFALO,NY,14203.0,NaN,11125,6721.0,09/09/9999,8,337000,337000,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Documentation: [pandas.DataFrame.set_index](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.set_index.html)

In [7]:
# Set index as column SBL
df.set_index('SBL', drop=True, append=False, inplace=True, verify_integrity=True)

In [8]:
df.head()

,Tax District,Print Key,Front,Depth,Property Class,Property Class Description,Previous Property Class,Owner1,Owner2,Previous Owner,Mail1,Mail2,Mail3,Mail4,House Number,Street,Address,City,State,Zipcode,Zipcode Extension,Deed Book,Deed Page,Deed Date,Roll,Land Value,Total Value,Sale Price,Year Built,First Story Area,Second Story Area,Total Living Area,Overall Condition,Building Style,Heat Type,Basement Type,# of Stories,# of Fireplaces,# of Beds,# of Baths,# of Kitchens,Council District,Police District,Census Tract,Census Block Group,Census Block,Neighborhood,Latitude,Longitude,Location
SBL,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1113100012001122A,147003.0,111.31-12-1.122/A,0.00,0.00,873,GAS MEAS STATION,873.0,NATIONAL FUEL GAS DIST,CORP,NaN,NaN,NaN,6363 MAIN ST,"WILLIAMSVILLE, NY",725.0,WASHINGTON,NaN,BUFFALO,NY,14203.0,NaN,NaN,NaN,09/09/9999,6,0,13006,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1011500001001111,147012.0,101.15-1-1.111,0.00,0.00,330,COMMERCIAL VACANT LAND,330.0,"AROUND THE CLOCK CAR WASH,INC.",NaN,NaN,NaN,NaN,6547 EMILY LN,"LOCKPORT, NY",119.0,WEX,NaN,BUFFALO,NY,14211.0,NaN,11144,9356.0,09/09/9999,1,2900,2900,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0785000008001000,147009.0,78.50-8-1,65.00,82.57,311,RESIDENTIAL VACANT LAND,NaN,THE MARRANO/MARC-EQUITY CORP.,NaN,NaN,NaN,NaN,2730 TRANSIT RD,"WEST SENECA, NY",142.0,RACHEL VINCENT,NaN,BUFFALO,NY,14216.0,NaN,11331,1637.0,09/09/9999,1,1700,1700,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1007300008009111,147003.0,100.73-8-9.111,50.00,200.00,311,RESIDENTIAL VACANT LAND,311.0,MARIAH LORETTA LLC,NaN,NaN,NaN,NaN,100 S WOODLAND RIDGE,"ELMA, NY",289.0,LOCUST,NaN,BUFFALO,NY,14204.0,NaN,11309,505.0,09/09/9999,1,3800,3800,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1321500002004000,147013.0,132.15-2-4,521.34,1184.60,340,INDUSTRIAL VACANT LAND,340.0,BUFFALO URBAN DEVELOPMENT CORP,NaN,NaN,NaN,NaN,275 OAK ST,"BUFFALO, NY",126.0,LABORERS WAY,NaN,BUFFALO,NY,14203.0,NaN,11125,6721.0,09/09/9999,8,337000,337000,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### (1) split available data into training + test set

notice that we call `learn` the training partition to avoid clash with train later on on train/val split

Documentation: [sklearn.model_selection.train_test_split](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html)

In [9]:
learn, test = train_test_split(df, test_size=0.25, random_state=22, shuffle=True, stratify=None)

In [10]:
learn.shape

(70396, 50)

In [11]:
test.shape

(23466, 50)

### (2) use train/val split as resampling method

In [12]:
# split "learn" into train + validation
train, val = train_test_split(learn, test_size=0.25, random_state=22, shuffle=True, stratify=None)

In [13]:
train.shape

(52797, 50)

In [14]:
val.shape

(17599, 50)

We use pickle filetype to save datatypes and indices

In [15]:
train.to_pickle("train_BuffaloProperty.pkl")

In [16]:
val.to_pickle("validation_BuffaloProperty.pkl")

In [17]:
test.to_pickle("test_BuffaloProperty.pkl")

In [18]:
df_val = pd.read_pickle("validation_BuffaloProperty.pkl")

In [19]:
df_val.head()

,Tax District,Print Key,Front,Depth,Property Class,Property Class Description,Previous Property Class,Owner1,Owner2,Previous Owner,Mail1,Mail2,Mail3,Mail4,House Number,Street,Address,City,State,Zipcode,Zipcode Extension,Deed Book,Deed Page,Deed Date,Roll,Land Value,Total Value,Sale Price,Year Built,First Story Area,Second Story Area,Total Living Area,Overall Condition,Building Style,Heat Type,Basement Type,# of Stories,# of Fireplaces,# of Beds,# of Baths,# of Kitchens,Council District,Police District,Census Tract,Census Block Group,Census Block,Neighborhood,Latitude,Longitude,Location
SBL,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1334600001006000,147013.0,133.46-1-6,50.0,155.0,210,ONE FAMILY DWELLING,210.0,HRYNCZAK PETRO (LE),HRYNCZAK JULIA (LE),NaN,NaN,NaN,27 CRYSTAL AVE,"BUFFALO, NY",27.0,CRYSTAL,NaN,BUFFALO,NY,14220.0,NaN,11109,1936.0,11/07/2005,1,7700,65000,1,1955.0,NaN,NaN,1066,3.0,1.0,2.0,4.0,NaN,0,3,1.0,NaN,SOUTH,District A,2,3,3005,Hopkins-Tifft,42.845672,-78.831177,"(42.84567227521914, -78.83117735751773)"
1007600006028000,147004.0,100.76-6-28,30.0,127.0,210,ONE FAMILY DWELLING,210.0,WILLIAMSVILLE PROPERTIES,NaN,NaN,NaN,NaN,3842 HARLEM RD #400-291,"BUFFALO, NY",578.0,WILSON,NaN,BUFFALO,NY,14211.0,NaN,11252,9228,09/12/2013,1,1700,12000,3000,1817.0,NaN,NaN,1498,2.0,8.0,2.0,3.0,NaN,0,2,1.0,NaN,FILLMORE,District C,166,2,2005,Broadway Fillmore,42.901118,-78.840372,"(42.90111849963285, -78.84037233811456)"
1337900001046000,147014.0,133.79-1-46,32.0,183.0,210,ONE FAMILY DWELLING,210.0,SPEIDEL EDWARD H,NaN,NaN,NaN,NaN,62 ALDRICH PL,"BUFFALO, NY",62.0,ALDRICH,NaN,BUFFALO,NY,14220.0,NaN,10915,2610,04/22/1997,1,6400,67000,64000,1920.0,NaN,NaN,1616,3.0,8.0,2.0,4.0,NaN,0,4,1.1,NaN,SOUTH,District A,6,4,4006,South Park,42.833233,-78.821461,"(42.833232834431946, -78.82146132555859)"
1106000001002200606,147001.0,110.60-1-2.2/606,5.0,239.0,210,ONE FAMILY DWELLING,210.0,BAUER LISA M,NaN,NaN,NaN,NaN,606 ADMIRALS WALK,"BUFFALO, NY",75.0,OJIBWA,NaN,BUFFALO,NY,14202.0,NaN,10970,3370.0,08/17/2000,1,12400,150000,133500,1991.0,NaN,NaN,1008,3.0,14.0,2.0,1.0,NaN,0,2,2.0,NaN,FILLMORE,District B,72.02,1,1006,Central,42.884581,-78.886420,"(42.88458058533622, -78.8864199240598)"
1004400001004000,147005.0,100.44-1-4,29.0,106.0,220,TWO FAMILY DWELLING,220.0,ROBINSON LINDA,NaN,NaN,NaN,NaN,162 KAY ST,"BUFFALO, NY",581.0,FERRY EAST,NaN,BUFFALO,NY,14211.0,NaN,11225,2056,06/20/2012,1,1000,22100,1,1900.0,NaN,NaN,2120,3.0,8.0,3.0,4.0,NaN,0,6,2.0,NaN,MASTEN,District C,35,2,2005,MLK Park,42.914422,-78.842605,"(42.914422066855444, -78.84260536602814)"